"""create initial domain schema

Revision ID: 0001_initial
Revises:
Create Date: 2026-09-26 12:36:23.165914
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "0001_initial"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "users",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("email", sa.Text(), nullable=False),
        sa.Column("email_normalized", sa.Text(), nullable=False),
        sa.Column("password_hash", sa.Text(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.CheckConstraint(
            "char_length(btrim(email)) >= 1", name=op.f("ck_users_email_not_blank")
        ),
        sa.CheckConstraint(
            "char_length(btrim(email_normalized)) >= 1",
            name=op.f("ck_users_email_normalized_not_blank"),
        ),
        sa.CheckConstraint(
            "updated_at >= created_at", name=op.f("ck_users_timestamps_ordered")
        ),
        sa.CheckConstraint("version >= 1", name=op.f("ck_users_version_positive")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_users")),
        sa.UniqueConstraint("email_normalized", name=op.f("uq_users_email_normalized")),
    )
    op.create_table(
        "categories",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column(
            "kind",
            sa.Enum("STANDARD", "TASK", "EVENT", "CAPTURE", name="category_kind"),
            nullable=False,
        ),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("name_normalized", sa.Text(), nullable=False),
        sa.Column("voice_command", sa.String(length=100), nullable=False),
        sa.Column("voice_command_normalized", sa.Text(), nullable=False),
        sa.Column("description", sa.String(length=1000), nullable=False),
        sa.Column("color", sa.String(length=7), nullable=False),
        sa.Column("icon", sa.String(length=100), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.CheckConstraint(
            "color ~ '^#[0-9A-F]{6}$'", name=op.f("ck_categories_color_format")
        ),
        sa.CheckConstraint(
            "char_length(btrim(description)) BETWEEN 1 AND 1000",
            name=op.f("ck_categories_description_length"),
        ),
        sa.CheckConstraint(
            "char_length(btrim(icon)) BETWEEN 1 AND 100",
            name=op.f("ck_categories_icon_length"),
        ),
        sa.CheckConstraint(
            "char_length(btrim(name)) BETWEEN 1 AND 100",
            name=op.f("ck_categories_name_length"),
        ),
        sa.CheckConstraint(
            "char_length(btrim(name_normalized)) >= 1",
            name=op.f("ck_categories_name_normalized_not_blank"),
        ),
        sa.CheckConstraint(
            "char_length(btrim(voice_command)) BETWEEN 1 AND 100",
            name=op.f("ck_categories_voice_command_length"),
        ),
        sa.CheckConstraint(
            "char_length(btrim(voice_command_normalized)) >= 1",
            name=op.f("ck_categories_voice_command_normalized_not_blank"),
        ),
        sa.CheckConstraint(
            "updated_at >= created_at", name=op.f("ck_categories_timestamps_ordered")
        ),
        sa.CheckConstraint("version >= 1", name=op.f("ck_categories_version_positive")),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_categories_user_id_users"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_categories")),
        sa.UniqueConstraint("user_id", "id", name=op.f("uq_categories_user_id_id")),
        sa.UniqueConstraint(
            "user_id",
            "name_normalized",
            name=op.f("uq_categories_user_id_name_normalized"),
        ),
        sa.UniqueConstraint(
            "user_id",
            "voice_command_normalized",
            name=op.f("uq_categories_user_id_voice_command_normalized"),
        ),
    )
    op.create_index(
        "uq_categories_user_id_special_kind",
        "categories",
        ["user_id", "kind"],
        unique=True,
        postgresql_where=sa.text("kind <> 'STANDARD'"),
    )
    op.create_table(
        "deletion_tombstones",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column(
            "entity_type",
            sa.Enum(
                "CATEGORY",
                "TAG",
                "ENTRY",
                "ENTRY_TAG",
                "SAVE_PREFERENCE",
                "CAPTURE_CORRECTION",
                name="tombstone_entity",
            ),
            nullable=False,
        ),
        sa.Column("entity_id", sa.UUID(), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("deleted_version", sa.Integer(), nullable=False),
        sa.CheckConstraint(
            "deleted_version >= 2",
            name=op.f("ck_deletion_tombstones_deleted_version_minimum"),
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_deletion_tombstones_user_id_users"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_deletion_tombstones")),
        sa.UniqueConstraint(
            "user_id",
            "entity_type",
            "entity_id",
            name=op.f("uq_deletion_tombstones_user_id_entity_type_entity_id"),
        ),
    )
    op.create_table(
        "save_preferences",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column(
            "mode",
            sa.Enum("FAST_FORWARD", "PREVIEW_BEFORE_SAVE", name="save_mode"),
            nullable=False,
        ),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.CheckConstraint(
            "updated_at >= created_at",
            name=op.f("ck_save_preferences_timestamps_ordered"),
        ),
        sa.CheckConstraint(
            "version >= 1", name=op.f("ck_save_preferences_version_positive")
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_save_preferences_user_id_users"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_save_preferences")),
        sa.UniqueConstraint("user_id", name=op.f("uq_save_preferences_user_id")),
    )
    op.create_table(
        "tags",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("name_normalized", sa.Text(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.CheckConstraint(
            "char_length(btrim(name)) BETWEEN 1 AND 100",
            name=op.f("ck_tags_name_length"),
        ),
        sa.CheckConstraint(
            "char_length(btrim(name_normalized)) >= 1",
            name=op.f("ck_tags_name_normalized_not_blank"),
        ),
        sa.CheckConstraint(
            "updated_at >= created_at", name=op.f("ck_tags_timestamps_ordered")
        ),
        sa.CheckConstraint("version >= 1", name=op.f("ck_tags_version_positive")),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_tags_user_id_users"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_tags")),
        sa.UniqueConstraint("user_id", "id", name=op.f("uq_tags_user_id_id")),
        sa.UniqueConstraint(
            "user_id", "name_normalized", name=op.f("uq_tags_user_id_name_normalized")
        ),
    )
    op.create_table(
        "entries",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("category_id", sa.UUID(), nullable=False),
        sa.Column("occurred_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("content", sa.String(length=10000), nullable=False),
        sa.Column(
            "task_status",
            sa.Enum("PENDING", "IN_PROGRESS", "DONE", name="task_status"),
            nullable=True,
        ),
        sa.Column(
            "task_recurrence",
            sa.Enum("ONCE", "RECURRING", name="task_recurrence"),
            nullable=True,
        ),
        sa.Column("capture_session_id", sa.UUID(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.CheckConstraint(
            "(task_status IS NULL) = (task_recurrence IS NULL)",
            name=op.f("ck_entries_task_fields_paired"),
        ),
        sa.CheckConstraint(
            "char_length(btrim(content)) BETWEEN 1 AND 10000",
            name=op.f("ck_entries_content_length"),
        ),
        sa.CheckConstraint(
            "updated_at >= created_at", name=op.f("ck_entries_timestamps_ordered")
        ),
        sa.CheckConstraint("version >= 1", name=op.f("ck_entries_version_positive")),
        sa.ForeignKeyConstraint(
            ["user_id", "category_id"],
            ["categories.user_id", "categories.id"],
            name=op.f("fk_entries_user_id_category_id_categories"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_entries_user_id_users"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_entries")),
        sa.UniqueConstraint(
            "user_id",
            "id",
            "capture_session_id",
            name=op.f("uq_entries_user_id_id_capture_session_id"),
        ),
        sa.UniqueConstraint("user_id", "id", name=op.f("uq_entries_user_id_id")),
    )
    op.create_table(
        "capture_corrections",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("entry_id", sa.UUID(), nullable=False),
        sa.Column("capture_session_id", sa.UUID(), nullable=False),
        sa.Column(
            "field",
            sa.Enum(
                "CATEGORY_ID",
                "OCCURRED_AT",
                "CONTENT",
                "TAG_IDS",
                name="correction_field",
            ),
            nullable=False,
        ),
        sa.Column(
            "interpreted_value", postgresql.JSONB(astext_type=sa.Text()), nullable=True
        ),
        sa.Column(
            "accepted_value", postgresql.JSONB(astext_type=sa.Text()), nullable=True
        ),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.CheckConstraint(
            "updated_at = created_at",
            name=op.f("ck_capture_corrections_timestamps_equal"),
        ),
        sa.CheckConstraint(
            "version = 1", name=op.f("ck_capture_corrections_version_one")
        ),
        sa.ForeignKeyConstraint(
            ["user_id", "entry_id", "capture_session_id"],
            ["entries.user_id", "entries.id", "entries.capture_session_id"],
            name=op.f(
                "fk_capture_corrections_user_id_entry_id_capture_session_id_entries"
            ),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_capture_corrections_user_id_users"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_capture_corrections")),
        sa.UniqueConstraint(
            "entry_id",
            "capture_session_id",
            "field",
            name=op.f("uq_capture_corrections_entry_id_capture_session_id_field"),
        ),
    )
    op.create_table(
        "entry_tags",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("entry_id", sa.UUID(), nullable=False),
        sa.Column("tag_id", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.CheckConstraint(
            "updated_at = created_at", name=op.f("ck_entry_tags_timestamps_equal")
        ),
        sa.CheckConstraint("version = 1", name=op.f("ck_entry_tags_version_one")),
        sa.ForeignKeyConstraint(
            ["user_id", "entry_id"],
            ["entries.user_id", "entries.id"],
            name=op.f("fk_entry_tags_user_id_entry_id_entries"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["user_id", "tag_id"],
            ["tags.user_id", "tags.id"],
            name=op.f("fk_entry_tags_user_id_tag_id_tags"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_entry_tags_user_id_users"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_entry_tags")),
        sa.UniqueConstraint(
            "entry_id", "tag_id", name=op.f("uq_entry_tags_entry_id_tag_id")
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("entry_tags")
    op.drop_table("capture_corrections")
    op.drop_table("entries")
    op.drop_table("tags")
    op.drop_table("save_preferences")
    op.drop_table("deletion_tombstones")
    op.drop_index(
        "uq_categories_user_id_special_kind",
        table_name="categories",
        postgresql_where=sa.text("kind <> 'STANDARD'"),
    )
    op.drop_table("categories")
    op.drop_table("users")
    for enum_name in (
        "correction_field",
        "task_recurrence",
        "task_status",
        "save_mode",
        "tombstone_entity",
        "category_kind",
    ):
        postgresql.ENUM(name=enum_name).drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
